### ISSUE TITLE
Create Project Documentation

### ISSUE THREAD

**Issue by NamanhTran** [NamanhTran/Lexical-Analyzer#4]
## Dependency
Project needs to be completed.

## Overview
2-3 pages. Need to include results of test cases somewhere in the document.

## Action Items
- [x] Problem Statement
- [x] How to use your program
- [x] Design of your program 
- [x] Any Limitations
- [x] Any shortcomings 

## Resources/Instructions
[Google Doc](https://docs.google.com/document/d/1ZBB3lhCH0ILGwNi8Xo_9AMK-OITyaoWf3r9-t10udbo/edit?usp=sharing)

**Comment by leederrick1** [comment]
I'm gonna go ask the prof about the documentation!

**Comment by NamanhTran** [comment]
Closed since documentation is done.
