### ISSUE TITLE
Initial File Reading

### ISSUE THREAD

**Issue by bluebayani** [NamanhTran/Lexical-Analyzer#7]
## Overview
Read in source code and write out content to a `std::string` variable.

## Action Items
- [x] Create new header for this function.
- [x] Read in file.
- [x] Check if file isn't empty.
- [x] Write content to `std::string` variable.
- [x] Return the `std::string` with the file contents.
- [x] Test the function for correct output.

## Assumptions
- You will be handed a `std::string` with the path of the file.
  - ex: "test.txt", "./tests/test1.txt"

## Resources/Instructions
[Assignment 1 Resource](https://docs.google.com/document/d/1xiTCfBD521B0uGmJeqGESm8vzt6ac52hYFxIkPV13eM/edit?usp=sharing)

**Comment by NamanhTran** [comment]
I think we can split this up into 3 issues. 

- one for the initial file reading from the input text file.
- one for removing comments, newlines and trailing white spaces.
- one for converting the symbol table into the required text file.

What do you think?

**Comment by bluebayani** [comment]
That sounds good!
