### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by bluebayani** [NamanhTran/Lexical-Analyzer#8]
## Overview
Create regular expression strings to identify required tokens.

## Action Items
- [ ] Create regular expressions for:
  - [ ] Keywords
  - [ ] Identifiers
  - [ ] Separators
  - [ ] Operators
  - [ ] Digits (Real and Float)
- [ ] Create text file append each regular expression strings for each tokens into the file.

## Resources/Instructions
[Assignment 1 Resource](https://docs.google.com/document/d/1xiTCfBD521B0uGmJeqGESm8vzt6ac52hYFxIkPV13eM/edit?usp=sharing)
[Hackernoon's guide for Regular Expression](https://hackernoon.com/a-programmers-guide-to-regex-or-regular-expressions-0daw30be)
[Online Regex](https://regexr.com/)

**Comment by NamanhTran** [comment]
I am kind of confused by what this issue is asking here. According to the google document linked in the resources, it's already been identified.

Are you referring to creating the regular expressions to match all of the action items lists?

**Comment by bluebayani** [comment]
yes thats what i meant

**Comment by NamanhTran** [comment]
I will be closing this issue since it is no longer relevant to the project anymore.
